# Generated by Django 5.2.4 on 2025-09-26 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.invite')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('going', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.guest')),
            ],
        ),
    ]
