# Generated by Django 5.2.4 on 2025-09-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('spotify_link', models.URLField()),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.invite')),
            ],
        ),
    ]
