# Generated by Django 5.2.4 on 2025-09-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='spotify_link',
            field=models.URLField(blank=True, help_text='If you can provide one it will be easier for us!'),
        ),
    ]
