# Generated by Django 5.2.4 on 2026-04-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_music_spotify_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements',
            field=models.TextField(blank=True, default=''),
        ),
    ]
